greatghoul/remote-working

README.md

fix spell error: Stackoverflwo=> Stackoverflow #21

---

weekly/issue-18.md

add peachapp recruitment

---

README.md

新添加一篇经验分享，来自：https://twitter.com/lenazun/status/752595703524884480。

Add Working Remotely ideas by Lena

---

README.md

Add a presentation from employees at Travis CI: https://lislis.de/talks/remotiest/

Add The Remotiest Workflow

---

README.md

homebrew 目前维护者的演讲，里面既有 YouTube 也有 SpeakerDeck，不过 slides 是配演讲的，姑且算在了影音分类。

Add remote-working-what-why-how

---

README.md

把 Protobia Tech 修正为 ProtobiaTech

修正 ProtobiaTech 团队名称

---

README.md

https://nozbe.com/zh-cn/blog/remote-work-facts-myths/

添加新文章：9个关于远程工作的事实和谣言

---

README.md

https://segmentfault.com/a/1190000013648364
远程工作的模式，在中国的确是比较超前的，如果公司不能交社保，遇到买房、出国这些
事情的时候就会比较被动。不过可能通过一些代办社保的公司解决，虽然比较麻烦。

新文章：记一次参加 CrossOver Meetup 的经历

---

README.md

https://www.jianshu.com/p/ba06a2d0d681
远程工作所能带来的好处太多了：节省通勤的时间和金钱，更好规划员工自己的生活，
更加正确地衡量员工的能力和工作态度。。而这些优势，能够吸引更多世界各地的人才，
让一群优秀的团队成员合作，是取得巅峰绩效的关键。

添加新文章：远程工作才是实现 高效工作&幸福生活 的有效途径

---

README.md

https://www.jianshu.com/p/c9bf5634191b
程序员客栈的远程工作经验，什么样的人适合远程工作及如何提升远程开发/外包的成功率。

新文章：什么样的人适合做远程工作

---

README.md

https://news.cnblogs.com/n/583905/

添加文章：为什么越来越多的创业公司选择远程工作？

---

README.md

添加远程团队：https://token.im/careers

---

README.md

更新列表说明，添加几个更新渠道

---

README.md

feat: add adventurer.tech

---

README.md

https://yizaoyiwan.com/discussions/12148

添加文章：自由职业第三年，患上拖延证，加上经济寒冬

---

README.md

https://mp.weixin.qq.com/s/e2ncLcfdyZdxkKOyScHgAw
同时添加了公众号：数字游民剑伟

添加文章：从间隔年到数字游民：22岁时环游中国，30岁开始边旅行边工作

---

README.md

https://juejin.im/post/5c09d75b51882516cd70d87b

添加文章：异地技术团队高效协作的经验分享

---

README.md

https://mp.weixin.qq.com/s/4Az5QeSjqsQ13xpBjpedzw

添加文章：如何做好一个远程工作的Project Manager (项目管理人)？

---

README.md

https://mp.weixin.qq.com/s/-7uyue8y5XAgd56AoDQFZA

添加文章：一点自由 | 阳志平 心志工具箱

---

README.md

添加远程团队：猩际教育

---

README.md

https://zhuanlan.zhihu.com/p/61226226

添加文章：五年自由职业感悟：赚钱是最深刻的修行

---

README.md

https://www.bilibili.com/video/av49314633

什么是远程工作，我是如何远程工作的？

---

README.md

https://zhuanlan.zhihu.com/p/63501230

添加文章：为什么你老板还没有推行在家办公？一个传播学角度的解释

---

README.md

* 我近期反省了之前做课的策略，如果想做知识付费软件开发培训，可以看一下
* 增加我厂 OpenResty Inc 的新 JD

change: added my blog post and OpenResty JD.

---

README.md

https://mp.weixin.qq.com/s/uf9v-bARQWlWPlNieEy0wg

添加文章：被动收入对自由工作的人有多重要

---

README.md

https://mp.weixin.qq.com/s/rSusDM4-r5hxAG5TGgM4UQ

添加文章：看完这本书，才意识到我为什么要死扛自由职业

---

README.md

https://www.jianshu.com/p/19b86daad313

添加文章：远程工作之痛 —— 这麽简单的功能你要六小时？

---

README.md

https://dimension.im/
相关招聘
https://github.com/APBCD/jobs/issues/13

添加团队：Dimension

---

README.md

https://blog.minghe.me/a-day-of-remote-worker/

添加文章：远程工作者的一天

---

README.md

- remote-jobs：远程公司
- open-source-jobs: 远程开源项目

docs: 添加remote-jobs与open-source-jobs: 远程公司与远程开源项目列表链接

---

README.md

WORKFUN  链接已失效
